CREATE TYPE scene AS ENUM (
    'Nature',
    'City',
    'City-Nature'
);

CREATE TABLE sprites_list (
  sprite_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  sprite_name TEXT NOT NULL,
  sprite_url TEXT NOT NULL,
  category scene NOT NULL
);