CREATE TABLE soundscapes (
  id BIGSERIAL PRIMARY KEY,
  soundscape_name TEXT NOT NULL,
  stems JSONB NOT NULL
);

-- CREATE TABLE soundscapes_with_categories (
--   id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
--   soundscape_id INTEGER,
--   category_id INTEGER,
-- );
 
-- CREATE TABLE categories_with_sprites (
--   id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
--   sprites_id INTEGER,
--   category_id INTEGER,
-- );

-- Make sure table migrations run in order. The ones dependant on other tables existing run after the creation of the relations 
-- eg - categories table must be created before soundscapes table