CREATE TABLE IF NOT EXISTS soundscape_music (
  soundscape_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  soundscape_name text,
  kick jsonb,
  snare jsonb,
  percussion jsonb,
  cymbals jsonb,
  accessory jsonb,
  melody jsonb,
  harmony jsonb,
  instrument jsonb,
  atmosphere jsonb
);